notifications:
email: false
language: python
python: 3.6
script:
- errors=`find . -name "*.py" -exec flake8 --max-line-length=120 --ignore=E225,E226,W292 \;`
- |
    if [ -z "$errors" ]
    then
        true
    else
        echo "$errors"
        false
    fi
